language: groovy
before_script:
 - chmod +x grailsw
script: ./grailsw refresh-dependencies
     && ./grailsw test-app
branches:
    only:
        - master
        - develop
        - feature/ui
     
